### ISSUE TITLE
Dont show Press any key to continue at the end

### ISSUE THREAD

**Issue by ricardopolo** [Code52/pretzel#191]
When you are trying to run `pretzel.exe bake` from a script in an automated deployment process the script gets stucked because the message `Press any key to continue...`

So do you have a silent parameter or a non confirmation option?

**Comment by shiftkey** [comment]
What version are you running?

I don't believe this should be the intended behaviour anymore - we should only do this when we're doing `taste` because that listens for filesystem changes and rebuilds the site, and that has it's [own rules](https://github.com/Code52/pretzel/blob/master/src/Pretzel/Commands/TasteCommand.cs#L94-L99).

So I'd :fire: [these lines](https://github.com/Code52/pretzel/blob/master/src/Pretzel/Program.cs#L69-L83) unless @laedit or @JakeGinnivan can think of specific reasons to keep it around.

**Comment by ricardopolo** [comment]
@shiftkey It was my fault. I was running a version that I compile using "Debug" instead "Release". In Debug it always show Plese Wait, in Release it works. So, excuse me, this issue is invalid.

**Comment by shiftkey** [comment]
@ricardopolo I'm glad you were able to resolve it. I still think this can be removed - let's see what the others think...

**Comment by ricardopolo** [comment]
@shiftkey btw would be nice if you recommend compile in Release configuration instead of Debug (default) in the Readme of the project

**Comment by laedit** [comment]
@shiftkey I am ok with that, I don't think these lines have any value.

**Comment by markvantilburg** [comment]
Well if you run it from visual studio with F5, you might not see any output without the wait for keypress...

**Comment by laedit** [comment]
Sorry for the changing opinion but finally I think that @markvantilburg is right: the mandatory keypress can be useful in debug mode.
As suggested by @ricardopolo we can just compile in Release mode by default in the build.cmd.
