### ISSUE TITLE
Examples of category and tag pages

### ISSUE THREAD

**Issue by AndreyAkinshin** [Code52/pretzel#208]
It would be very cool, If you add examples of speical pages for categories and tags. For example, I have category `dotnet`, `dev`, `r`. And I want to find the way of autogenerating pages `/blog/dotnet/`, `/blog/dev/`, `blog/r/` with lists of corresponded posts. And I want an example of same thing for tags (like `/tag/<tag name>/`). Can you put some examples in the repo?

**Comment by laedit** [comment]
It's not part of Pretzel but it can be done by creating a custom `IContentTransform`.

**Comment by AndreyAkinshin** [comment]
Do you have any examples of `IContentTransform` using?

**Comment by laedit** [comment]
My mistake, it's `IContent`, sadly there is no documentation for the moment but you have the [`LessTransform`](https://github.com/Code52/pretzel/blob/master/src/Pretzel.Logic/Minification/LessTransform.cs) class as example.
You have to iterate on `siteContext.Tags` and `siteContext.Categories` and writes files through the `IFileSystem`.

In order to use it with Pretzel you have to create a dll with it and drop it in a `_plugins` folder at the root of your site.

**Comment by AndreyAkinshin** [comment]
Thanks!
