### ISSUE TITLE
Merging of efforts with Sandra.Snow and others

### ISSUE THREAD

**Issue by JacobVoracek** [Code52/pretzel#227]
Hi guys, 

I was looking around for static site generator written in C#/F# and found that there isn't a go to option like Jekyll or Middleman or Octopress. Pretzel is pretty good but it's not quite there yet (especially as far as the ease of use/on-boarding experience for newbies goes). As I was looking around, I found a few other options that are also trying to replicate Jekyll-like functionality in .NET and wanted to see if there is any interest in maybe merging efforts and working together. I figured I would open an issue to get some discussion going. 

[Sandra.Snow](https://github.com/Sandra/Sandra.Snow) and [FsBlog](https://github.com/fsprojects/FsBlog) seem to be the two other projects that are the most mature but there are others like [Baker](https://github.com/Kelindar/misakai-baker), [Lithogen](https://github.com/PhilipDaniels/Lithogen), [etc](https://github.com/search?l=C%23&o=desc&q=static+site+language%3AC%23&ref=advsearch&s=updated&type=Repositories&utf8=%E2%9C%93). that are at various level of maturity. Even if there isn't much interest in combing efforts wholesale, maybe there is an opportunity to cooperate on templates, themes, plugins, etc. 

Including @jchannon, @phillip-haydon, @tpetricek and @kelindar for their thoughts.

**Comment by JacobVoracek** [comment]
Adding a few more people: @PhilipDaniels, @robmen, @bcwood, @ipavl, @adamkrieger.

**Comment by tpetricek** [comment]
Building something that makes C#/F# blogging easy would be great! 

FsBlog does a good job at processing Markdown (in a highly customizable way - because you can transform the documents) using [F# Formatting](github.com/tpetricek/FSharp.Formatting) and at formatting F# code (using the compiler service) - this is pretty much the main reason why anybody writing about F# should use it - because it also produces code tool tips etc. It does not do very good job at the other things (like templating).

So, if there is something that the "perfect system" should have from FsBlog, it is probably the Markdown processing model and the F# code formatting.

The Markdown processing idea is that it runs the parser and gives you back a document that you can transform in any way you wish. There is a [short example in the docs](http://tpetricek.github.io/FSharp.Formatting/markdown.html) that collects all links (you could generate "References" section from this). A bigger example is [FsReveal](http://fsprojects.github.io/FsReveal/) which does some special transformations on the document to turn it into reveal.js presentation.

**Comment by adamkrieger** [comment]
Thanks for bringing me into the discussion. I'm interested in combining efforts. 

Fable was written over the course of a few weekends. It's pretty short on capabilities, but I learned a number of things from it.
- FParsec is a lot of fun to work with, and allows the developer to write parsers in EBNF. This kept things pretty conventional and expandable.
- Jekyll can get fragmented across ruby, python, and even more interpreters, depending on what plugins are needed. Keeping implementation homogenous reduces complexity for the user.
- Mono .Net brings a very large audience and can keep the user's ramp-up period, and learning curve, short.

Wanted to get in touch. I'll take a look at the open projects you've mentioned.

Thanks again,
Adam Krieger

**Comment by Kelindar** [comment]
I agree, something simple for blogging would be great. 

My personal takeaway was the architecture: a static generator can be seen as a stream processing system that should be easily parallelised and customised. That way any plugin can be just defined as a stream processor taking an input and producing an output.

A nice thing would be to have a repository (nuget?) for plugins, themes etc. Something that allows easy  contribution/discovery.

**Comment by PhilipDaniels** [comment]
Thanks for starting this discussion. I am the author of Lithogen.

I got into this space because I wanted to write a static site for my ConfigZilla project - http://philipdaniels.com/configzilla/index.html - Jekyll didn't seem suitable, being really geared towards blogging, and I didn't want to learn Ruby. Alas, at the time there didn't seem to be anything suitable/active enough in the .Net space, so I looked into various Node engines, of which Docpad and Assemble.IO are probably the best. I used Docpad to build ConfigZilla's website and Assemble.IO to build my Git cheatsheet at http://philipdaniels.com/gitcheatsheet/ - though I have now rebuilt this with Lithogen. I decided to build my own site generator because of a nasty experience with Docpad - I accidentally upgraded some of the node modules and everything broke and I had no way to update my site. Not nice. Assemble.IO is pretty cool, but not really actively maintained. And Grunt is a colossal PITA.

My aim for Lithogen is to finish the core functionality needed for static site generation and then it will be easy to build a blog engine on top of it. I just got LiveReload working tonight, though it's still a hack. The main things left to do are

* Support Jade and Highlight.JS (needed so I can rebuild ConfigZilla's website)
* Write a whole bunch of Handlebars helpers
* Come to a decision on how to allow elegant extensibility with Node/npm.
* Beef up the Markdown processor
* Write its own website!

One thing to be aware of is that the ground may shift significantly when ASP.vNext is finally released - although I suspect that inflicting Grunt on people will not be seen as a forwards step no matter how Microsoft tries to spin it :-)

@JacobVoracek sharing themes might be a good idea. If a theme is just CSS + a layout. Of course, raises the question of what format the layout is in.

@Kelinder: That is in fact how Lithogen works (I stole the idea from Assemble.IO). A view is read from disk then passed through a series of processors f(g(h(file)), where the sequence is defined by the file extensions. At least that is the idea, currently support razor, handlebars and markdown. Lithogen and Baker are probably at about the same level at the moment.

**Comment by JacobVoracek** [comment]
I was hoping there would be more interest but regardless, it seems like there is at least some interest in maybe merging efforts. So the next question obviously, is where and how? FsBlog and Fable are both F#. Baker and Lithogen are C#. I don't think the choice of language really matters as long as the final solution is .NET/Mono compatible. Thoughts? 

@tpetricek I know one of the issues with FsBlog is performance but that may partly be because of the dependency on Razor in [F# Formatting](https://github.com/tpetricek/FSharp.Formatting). I recall there being some discussion about maybe replacing Razor with DotLiquid. Is that still the case?  

@laedit @shiftkey @vikingcode @AndreyAkinshin Thoughts?

**Comment by JacobVoracek** [comment]
I also wonder if something like @madskristensen's [MiniBlog](https://github.com/madskristensen/MiniBlog) might be close enough to a static site that he might be interested in this as well.

**Comment by vikingcode** [comment]
I'm not saying I'm not interested, but I will say I'm not at the point where programming of any sort is something I do more than once a month these days. I *can* waffle on about a bunch of lofty goals, but I 'm sure somebody else could fill that role. Remember, the name of pretzel was largely decided because I was *hungry*. No, I'm not joking. 

To me one of the bigger differences between the various projects is not what language they're written in but the goals. Pretzel *was* at least at one point in time (and currently is, AFAIK) meant to be a drop in replacement for Jekyll. Oh sure it did some auxiliary formats and the such, but that was more the byproduct of the architecture.

Others like Sandra.Snow and FsBlog seem to be Jekyll-*inspired*.

To me, that'd be the fundamental key difference to either 'merge' or create a new combined project from - do you go for something thats Jekyll compatible as its goal, or strives to be more than Jekyll and learn from some of the mistakes-or-ruby specifics that it has?

**Comment by vikingcode** [comment]
Oh and I agree that running on mono should probably be a key goal. Having a git post-receive hook that then builds the site ala gh-pages that will run on digitalocean would rock my socks.

**Comment by phillip-haydon** [comment]
I'm not... not interested (double negative) I got the email while I was on holiday for my birthday. So ended up forgetting about it.

My fear of merging is having too many opinionated people. I wrote Snow to re-create in a way, what Jekyll is, and add features I wanted to make things easier. i.e self-hosting for testing after a compile, 'series' to handle a group of posts without having to go back and update old posts. etc.

I would hate to have to fork a merged effort down the road to implement what i want/need and/or move the project back on track of being just a static file generator and not some full blown attempt to do things outside of what it was originally designed to do.

**Comment by ipavl** [comment]
Although the [static site generator I wrote](https://github.com/ipavl/flamel) was more of an F# experimentation and meant to be rather simplistic, I'd be interested in collaborating on a more "proper" project.

**Comment by laedit** [comment]
Like @vikingcode and @phillip-haydon said I think that all static site generator on this thread was created with a certain purpose. So I don't think that a merge can be achieved if all the purpose are different.

But we can collaborate at some point, like sharing a common layout and themes.
