### ISSUE TITLE
Pretzel doesn't handle trailing slashes on pages

### ISSUE THREAD

**Issue by idvorkin** [Code52/pretzel#289]
For example the following works:

    http://locahost:8080/page1 

But with a trailing slash it fails:

    http://locahost:8080/page1/

**Comment by laedit** [comment]
Thanks for reporting it.
It's happening on the `taste` command?
Do you have an error with a stacktrace or just a 404?
It's likely due to Firefly, the currently used local server which should be replace by Nowin, it has caused other [issues](https://github.com/Code52/pretzel/issues/147).
If you have time a PR is more than welcome :smile:

**Comment by idvorkin** [comment]
Yup this is with taste.
No stack trace, just  a very simple page, which is coming back with status code 200, looks like: 

     Page not found: /welcome-to-holland/

**Comment by laedit** [comment]
Have you tried with the version 0.3.0?

**Comment by idvorkin** [comment]
Sweet - Fixed in 0.3.0 - Thanks!
