### ISSUE TITLE
Problems with Permalinks

### ISSUE THREAD

**Issue by hutchcodes** [Code52/pretzel#295]
I'm having problems getting permalinks to work they way I expect.

value|expected|actual
-------|-----------|--------
:year|year from the filename|year of the lastupdate to the file
:month|month from the filename|month of the lastupdate to the file
:title|title from the post's frontmatter|name of the file (including year_month)

:year and :month might be a problem with my expectations as I see I can put the `date` in the frontmatter.  Though having a "permalink" based on the last modified date of a file seems less permenant than I'd like.

:title really should pull from the frontmatter, with maybe a separate keyword for filename.

I'm coming from PieCrust CMS and I'm here to contribute. I'd be happy to make the changes but don't want to go running off without checking in.

**Comment by laedit** [comment]
Thanks for the report and welcome to Pretzel :smiley: 

`:year` and `:month` should come from the lastupdate of the file only if the filename doesn't have a date. Can you provide a way to reproduce the issue?

For the title it's the expected behavior: Pretzel is based on Jekyll and it's the way Jekyll is doing it, unless it has changed recently.

But it is possible to add a parameter in the config file to use the title from the frontmatter instead of the name of the file to build the url.
What do you

**Comment by hutchcodes** [comment]
I figured out the date issue. My files are in folders by year and only have month-day in the file name. I'll either add the date to the frontmatter or add the year to the filename as part of my migration.

I'll add a :posttitle variable, if the title isn't in the post's frontmatter fall back to file name.

**Comment by laedit** [comment]
Ok then :smiley:

**Comment by hutchcodes** [comment]
Scratch that. No changes necessary. I noticed that if I have the full date in the file name it strips out the date from the filename and just uses the file name.  Moral of the story is posts need to be named yyyy-mm-dd-[permalink]
