### ISSUE TITLE
Environments not working

### ISSUE THREAD

**Issue by dario-l** [Code52/pretzel#307]
Setting 
```
--configuration=debug
```
or other value doesn't reflect on baked site. Is it really implemented?

**Comment by markvantilburg** [comment]
This is not merged yet; see https://github.com/Code52/pretzel/pull/302

**Comment by laedit** [comment]
As @markvantilburg said, this feature is part of #302 which will not be merged. Some of the features will be included when I'll have the time to merge them properly or if someone propose a clean PR with only one feature.
I will delete the wiki pages, since they are documenting features not included in the released version.
