### ISSUE TITLE
Any value to this project in creating a "pretzel" tag on StackOverflow?

### ISSUE THREAD

**Issue by gburghardt** [Code52/pretzel#315]
I've been playing around with Pretzel for about a year, and really like it. I'm having problems finding help with problems. I see lots of activity on this project's GitHub issues, but these issues aren't coming up very well in search engine results.

I have the privilege on StackOverflow to create new tags, and I was going to create a question about using the `_data` directory (related issue: #302). Would adding the **pretzel** tag on StackOverflow be beneficial to this project at all? If so, is there a place to put a note about this tag? Maybe adding a section to the README about getting help?

**Comment by laedit** [comment]
Thanks for your interest in pretzel ! :smile: 
Sadly right now I am the only "active" maintainer and I don't really have the time to deal with Pretzel at this time.
So I don't know if a new tag on StackOverflow is a good think, I have though of it myself but since we are very few to know how to use Pretzel, I don't know if it will work on StackOverflow.
I let you decide, but if you think it is worth it please make a PR to add the information in the README.

**Comment by gburghardt** [comment]
Ok. Maybe when I play around with this more and become more accustomed to it I'll try to help maintain this. Thanks!
